apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mb-service.fullname" . }}
  labels:
    appName: {{ .Values.appName }}
    env: {{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      appName: {{ .Values.appName }}
      env: {{ .Values.environment }}
  template:
    metadata:
      labels:
        appName: {{ .Values.appName }}
        env: {{ .Values.environment }}
    spec:
      nodeSelector:
        intent: {{ .Values.environment }}-{{ .Values.riskLevel }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.imageName }}:{{ .Values.image.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
