apiVersion: v1
kind: Service
metadata:
  name: {{ template "mb-service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "mb-service.name" . }}
    environment: {{ .Values.environment }}
