apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "mb-service-4.fullname" . }}
  labels:
    appName: {{ template "mb-service-4.name" . }}
    env: {{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      appName: {{ template "mb-service-4.name" . }}
      env: {{ .Values.environment }}
  template:
    metadata:
      labels:
        appName: {{ template "mb-service-4.name" . }}
        env: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.imageName }}:{{ .Values.image.imageTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intent
                    operator: In
                    values:
                      - {{ .Values.environment }}-{{ .Values.intent }}
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
